- name: Copy logstash.yml
  copy:
    src: logstash.yml
    dest: "{{ elk_vars['config_directory'] }}-{{ elk_vars['elk_version'] }}/logstash.yml"
    owner: root
    group: root
    mode: 0755
    backup: yes
    force: yes
  notify:
    - restart logstash

- name: Copy logstash.conf
  copy:
    src: logstash-beats.yml
    dest: "{{ elk_vars['config_directory'] }}-{{ elk_vars['elk_version'] }}/logstash-beats.yml"
    owner: root
    group: root
    mode: 0755
    backup: yes
    force: yes
  notify:
    - restart logstash

- name: Deploy Logstash container
  docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:{{ elk_vars['elk_version'] }}
    state: started
    networks:
      - name: "{{ elk_vars['docker']['network'] }}"
    log_driver: json-file
    volumes:
     - "{{ elk_vars['config_directory'] }}-{{ elk_vars['elk_version'] }}/logstash.yml:/usr/share/logstash/config/logstash.yml:ro"
     - "{{ elk_vars['config_directory'] }}-{{ elk_vars['elk_version'] }}/logstash-beats.yml:/usr/share/logstash/pipeline/logstash.conf:ro"
    restart_policy: "{{ elk_vars['docker']['restart_policy'] }}"
    restart_retries: "{{ elk_vars['docker']['restart_retries'] }}"
