- name: Copy nginx.conf
  copy:
    src: nginx.conf
    dest: "{{ elk_vars['config_directory'] }}-{{ elk_vars['elk_version'] }}/nginx.conf"
    owner: root
    group: root
    mode: 0755
    backup: yes
    force: yes
  notify:
    - restart nginx

- name: Copy nginx allowed users
  copy:
    src: allowed_users
    dest: "{{ elk_vars['config_directory'] }}-{{ elk_vars['elk_version'] }}/allowed_users"
    owner: root
    group: root
    mode: 0755
    backup: yes
    force: yes
  notify:
    - restart nginx

- name: Deploy nginx container
  docker_container:
    name: nginx
    image: docker.io/nginx:{{ elk_vars['nginx_version'] }}
    state: started
    networks:
      - name: "{{ elk_vars['docker']['network'] }}"
    ports: ['0.0.0.0:80:80']
    volumes:
     - "{{ elk_vars['config_directory'] }}-{{ elk_vars['elk_version'] }}/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
     - "{{ elk_vars['config_directory'] }}-{{ elk_vars['elk_version'] }}/allowed_users:/etc/nginx/allowed_users:ro"
