- name: Create container service config directory
  file:
    path: "{{ elk_vars['config_directory'] }}-{{ elk_vars['elk_version'] }}"
    state: directory
    mode: 0755

- debug: var=elk_vars['docker']['network']
- debug: var=elk_vars['docker']['version']

- name: Create ELK network
  docker_network:
    name: "{{ elk_vars['docker']['network'] }}"

