---
client:
  hosts:
    - 172.18.0.2
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth: 'elastic:changeme'
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile: '/var/log/curator.log'
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
