CREATE USER IF NOT EXISTS slave@'%' IDENTIFIED BY 'replpwd';
GRANT SELECT, PROCESS, FILE, SUPER, REPLICATION CLIENT, REPLICATION SLAVE, RELOAD ON *.* TO slave@'%';
Flush Privileges; 
CHANGE MASTER TO
MASTER_HOST='mysql-master',
MASTER_USER='slave',
MASTER_PASSWORD='replpwd';
START slave;
